project_id = "ssgdyyiutipbapzkyqur"


[functions.register-student]
verify_jwt = false

[functions.reset-student-password]
verify_jwt = false

[functions.link-student]
verify_jwt = false

[functions.mark-attendance]
verify_jwt = false
